// <auto-generated />
using LegendsTrackerBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegendsTrackerBackend.Data.Migrations
{
    [DbContext(typeof(LegendsDBContext))]
    [Migration("20220628183421_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("LegendsTrackerBackend.Data.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultImg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeciesCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("LegendsTrackerBackend.Data.Variant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariantCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imgPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VariantId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("LegendsTrackerBackend.Data.Variant", b =>
                {
                    b.HasOne("LegendsTrackerBackend.Data.Species", "Species")
                        .WithMany("Variants")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("LegendsTrackerBackend.Data.Species", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
