// <auto-generated />
using LegendsTrackerBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegendsTrackerBackend.Data.Migrations
{
    [DbContext(typeof(LegendsDBContext))]
    [Migration("20220612215523_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("LegendsTrackerBackend.Data.Legend", b =>
                {
                    b.Property<int>("LegendID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiotCompanionID")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkinID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.HasKey("LegendID");

                    b.ToTable("Legends");

                    b.HasData(
                        new
                        {
                            LegendID = 1,
                            ImgPath = "https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/assets/loadouts/companions/tooltip_duckbill_base_variant7_tier2.littlelegends_11_22.png",
                            Level = 2,
                            Name = "Goodest Duckbill",
                            RiotCompanionID = "9e1423c2-d982-4db7-b478-f4d7235d51a1",
                            SkinID = 23,
                            Species = "Duckbill"
                        },
                        new
                        {
                            LegendID = 2,
                            ImgPath = "https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/assets/loadouts/companions/tooltip_choncc_honeybuzz_tier1.png",
                            Level = 1,
                            Name = "Honeybuzz Choncc",
                            RiotCompanionID = "3f358b24-6ca3-4943-85b1-8fb1981e93be",
                            SkinID = 16,
                            Species = "Choncc"
                        },
                        new
                        {
                            LegendID = 3,
                            ImgPath = "https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/assets/loadouts/companions/tooltip_chibijinx_firecracker_firecracker1_tier1.pie_c_12_2.png",
                            Level = 1,
                            Name = "Chibi Firecracker Jinx",
                            RiotCompanionID = "3496e511-29bb-4c43-8fdb-2bafa5626e57",
                            SkinID = 2,
                            Species = "Jinx"
                        });
                });

            modelBuilder.Entity("LegendsTrackerBackend.Data.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RiotMatchID")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
