// <auto-generated />
using LegendsTrackerBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegendsTrackerBackend.Data.Migrations
{
    [DbContext(typeof(LegendsDBContext))]
    [Migration("20220622184635_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("LegendsTrackerBackend.Data.Species", b =>
                {
                    b.Property<int>("speciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("defaultImg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("speciesName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("speciesId");

                    b.ToTable("species");

                    b.HasData(
                        new
                        {
                            speciesId = 23,
                            defaultImg = "https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/assets/loadouts/companions/tooltip_duckbill_base_variant7_tier2.littlelegends_11_22.png",
                            speciesName = "Goodest Duckbill"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
